name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools python3-wheel

    - name: Build package
      run: python3 setup.py sdist bdist_wheel

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
